const express=require('express')
const adminrouter=express.Router()
const authadmin=require('./admincontroller')
const isadmin=require('./isadmin')
const authuserexist=require('./checkinguserexist')
const adminuser=require('./adminuser')
adminrouter.get('/',authuserexist,isadmin,authadmin.checkingadmin)
adminrouter.get('/user',adminuser)
adminrouter.delete('/user/:id',authuserexist,isadmin,authadmin.deleteuser)
adminrouter.get('/user/individual/:id',authuserexist,isadmin,authadmin.updateuser)
adminrouter.patch('/user/update/:id',authuserexist,isadmin,authadmin.updatinguser)
adminrouter.get('/contact',authuserexist,isadmin,authadmin.contact)
adminrouter.delete('/contact/delete/:id',authuserexist,isadmin,authadmin.contactdelete)
module.exports=adminrouter